version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    allow: 
      - dependency-type: production
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: "/"
    allow: 
      - dependency-type: production
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1
